irc:
  enabled: false
  hostname: 192.168.1.121
  port: 6667
  nickname: c45_bot

token:
  secret: secret_here

plugins:
  - ping-pong:
      file: ping
      enabled: false
      command: ping
#  - next_plugin:
#      file: name
#      enabled: bool
#      command: command

acl:
  admins:
    - username#1234
#  role_name_here:
#    - username#1234

#guilds:
#  ignore:
#    - guild_name